// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0AuzyGCQ4zBAlO3Dp08eA0Q58T8SuLG4',
    appId: '1:394371494743:web:3aa9aee20361a3ee364412',
    messagingSenderId: '394371494743',
    projectId: 'contabilidad-9a8e6',
    authDomain: 'contabilidad-9a8e6.firebaseapp.com',
    storageBucket: 'contabilidad-9a8e6.appspot.com',
    measurementId: 'G-4RJCDESDJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArf6ngDV5nYdpkr-3fjYoRHmQ2wvcUDRY',
    appId: '1:394371494743:android:bb51d384252635e6364412',
    messagingSenderId: '394371494743',
    projectId: 'contabilidad-9a8e6',
    storageBucket: 'contabilidad-9a8e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wJzk-SYD_AReGTO-LE3NCCp4ZUktK4w',
    appId: '1:394371494743:ios:ed02750302b4a93a364412',
    messagingSenderId: '394371494743',
    projectId: 'contabilidad-9a8e6',
    storageBucket: 'contabilidad-9a8e6.appspot.com',
    iosBundleId: 'com.example.contabilidad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7wJzk-SYD_AReGTO-LE3NCCp4ZUktK4w',
    appId: '1:394371494743:ios:ed02750302b4a93a364412',
    messagingSenderId: '394371494743',
    projectId: 'contabilidad-9a8e6',
    storageBucket: 'contabilidad-9a8e6.appspot.com',
    iosBundleId: 'com.example.contabilidad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0AuzyGCQ4zBAlO3Dp08eA0Q58T8SuLG4',
    appId: '1:394371494743:web:9443d57f6731c4e8364412',
    messagingSenderId: '394371494743',
    projectId: 'contabilidad-9a8e6',
    authDomain: 'contabilidad-9a8e6.firebaseapp.com',
    storageBucket: 'contabilidad-9a8e6.appspot.com',
    measurementId: 'G-5YDT7JLCTF',
  );
}
